language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  allow_failure:
    - php: hhvm
    - php: nightly
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=1
  - php: 5.3
    env: WP_VERSION=4.2 WP_MULTISITE=0
  - php: 5.3
    env: WP_VERSION=4.1 WP_MULTISITE=0
  - php: 5.3
    env: WP_VERSION=4.0 WP_MULTISITE=0

before_script:
  - composer install --prefer-source --optimize-autoloader
  - bash tests/bin/install.sh gravitypdf_test root '' localhost $WP_VERSION

script:
 - vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist
 - vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist --group ajax

