name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    name: Build and Deploy Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: General debug information
        run: |
          npm --version
          node --version
          yarn --version
          curl --version
          git --version
          svn --version
          php --version
          composer --version

      - name: Build
        run: bash ./bin/package.sh $SOURCE_TAG
        env:
          SOURCE_TAG: ${{steps.tag.outputs.tag}}
          GH_CREDENTIALS: ${{ secrets.GH_CREDENTIALS }}

      - name: Deploy
        run: bash ./bin/deploy.sh
        env:
          PLUGIN: "gravity-forms-pdf-extended"
          SOURCE_TAG: ${{steps.tag.outputs.tag}}
          WP_ORG_USERNAME: ${{ secrets.WP_ORG_USERNAME }}
          WP_ORG_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}
