name: PHPUnit Tests

on:
  push:
    branches:
      - development
  pull_request:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

env:
  WP_DEVELOP_DIR: ./wordpress
  GF_LICENSE: ${{ secrets.GF_LICENSE }}

jobs:
  # Runs the PHPUnit tests for WordPress.
  #
  # Performs the following steps:
  # - Set environment variables.
  # - Sets up the environment variables needed for testing with memcached (if desired).
  # - Downloads the built WordPress artifact from the previous job.
  # - Unzips the artifact.
  # - Installs NodeJS 12
  # - Sets up caching for NPM.
  # _ Installs NPM dependencies using install-changed to hash the `package.json` file.
  # - Configures caching for Composer.
  # _ Installs Composer dependencies (if desired).
  # - Logs Docker debug information (about both the Docker installation within the runner).
  # - Starts the WordPress Docker container.
  # - Starts the memcached server after the Docker network has been created (if desired).
  # - Logs WordPress Docker container debug information.
  # - Logs debug general information.
  # - Logs the running Docker containers.
  # - Logs debug information about what's installed within the WordPress Docker containers.
  # - Install WordPress within the Docker container.
  # - Run the PHPUnit tests.
  # - Reports test results to the Distributed Hosting Tests.
  test-php:
    name: ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [ '8.0', '7.4', '7.3' ]
        os: [ ubuntu-latest ]
        include:
          # Report the results of the PHP 7.4 without memcached job.
          - php: '7.4'
            os: ubuntu-latest
            report: true
    env:
      LOCAL_PHP: ${{ matrix.php }}-fpm
      PHPUNIT_SCRIPT: php

    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log debug information
        run: |
          yarn --version
          node --version
          curl --version
          git --version
          svn --version
          php --version
          php -i
          locale -a

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache NodeJS modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: yarn install

      - name: Build Gravity PDF
        run: yarn build:production

      - name: Install / Setup Gravity PDF + WordPress
        run: |
          yarn env:install
          yarn env:install:phpunit

          if [ ${{ env.LOCAL_PHP }} == '8.0-fpm' ]; then
            echo "PHPUNIT_SCRIPT=php-composer" >> $GITHUB_ENV
          fi

      - name: General debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Log running Docker containers
        run: docker ps -a

      - name: Docker debug information
        run: |
          docker -v
          docker-compose -v
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm mysql mysql --version
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php php --version
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php php -m
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php php -i
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php locale -a

      - name: Run PHPUnit tests
        run: yarn test:${{ env.PHPUNIT_SCRIPT }} --verbose

      - name: Run (xDebug) tests
        if: ${{ matrix.report }}
        run: |
          LOCAL_PHP_XDEBUG=true yarn run test:php --verbose --coverage-clover=tmp/coverage/report-xml/php-coverage1.xml
          LOCAL_PHP_XDEBUG=true yarn run test:php --group ajax --verbose --coverage-clover=tmp/coverage/report-xml/php-coverage1.xml
          yarn test:js:coverage
          bash <(curl -s https://codecov.io/bash);
