name: PHPUnit Tests

on:
  push:
    branches:
      - development
  pull_request:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  WP_DEVELOP_DIR: ./wordpress
  GF_LICENSE: ${{ secrets.GF_LICENSE }}

jobs:
  # Runs the PHPUnit tests for WordPress.
  #
  # Performs the following steps:
  # - Set environment variables.
  # - Sets up the environment variables needed for testing with memcached (if desired).
  # - Downloads the built WordPress artifact from the previous job.
  # - Unzips the artifact.
  # - Installs NodeJS 12
  # - Sets up caching for NPM.
  # _ Installs NPM dependencies using install-changed to hash the `package.json` file.
  # - Configures caching for Composer.
  # _ Installs Composer dependencies (if desired).
  # - Logs Docker debug information (about both the Docker installation within the runner).
  # - Starts the WordPress Docker container.
  # - Starts the memcached server after the Docker network has been created (if desired).
  # - Logs WordPress Docker container debug information.
  # - Logs debug general information.
  # - Logs the running Docker containers.
  # - Logs debug information about what's installed within the WordPress Docker containers.
  # - Install WordPress within the Docker container.
  # - Run the PHPUnit tests.
  # - Reports test results to the Distributed Hosting Tests.
  test-php:
    name: ${{ matrix.php }}${{ matrix.multisite && ' multisite' || '' }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.0', '7.4', '7.3' ]
        os: [ ubuntu-latest ]
        multisite: [ false ]
        include:
          - php: '7.4'
            os: ubuntu-latest
            multisite: true
          - php: '7.4'
            os: ubuntu-latest
            multisite: false
            report: true
    env:
      LOCAL_PHP: ${{ matrix.php }}-fpm

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Log debug information
        run: |
          yarn --version
          node --version
          curl --version
          git --version
          svn --version
          php --version
          php -i
          locale -a

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache NodeJS modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      # This date is used to ensure that the Composer cache is refreshed at least once every week.
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: "Get last Monday's date"
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u --date='last Mon' "+%F")"

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-date-${{ steps.get-date.outputs.date }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Gravity PDF
        run: yarn build:production

      - name: Install / Setup Gravity PDF + WordPress
        run: |
          yarn env:install
          yarn env:install:phpunit

      - name: Install Composer dependencies
        run: |
          npm run env docker-run -- php composer --version
          # Install using `composer update` as there is no `composer.lock` file.
          if [ ${{ env.LOCAL_PHP }} == '8.1-fpm' ]; then
            npm run env docker-run -- php composer update --ignore-platform-reqs
          else
            npm run env docker-run -- php composer update
          fi

      - name: General debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Log running Docker containers
        run: docker ps -a

      - name: Docker debug information
        run: |
          docker -v
          docker-compose -v
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm mysql mysql --version
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php php --version
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php php -m
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php php -i
          docker-compose -f $WP_DEVELOP_DIR/docker-compose.yml run --rm php locale -a

      - name: Run PHPUnit tests
        run: yarn test:php --verbose
        continue-on-error: ${{ matrix.php == '8.1' }}

      - name: Run (xDebug) tests
        if: ${{ matrix.report }}
        run: |
          LOCAL_PHP_XDEBUG=true yarn run test:php --verbose --coverage-clover=tmp/coverage/report-xml/php-coverage1.xml
          LOCAL_PHP_XDEBUG=true yarn run test:php --group ajax --verbose --coverage-clover=tmp/coverage/report-xml/php-coverage1.xml
          yarn test:js:coverage
          bash <(curl -s https://codecov.io/bash);
